
(()=>{const C=window.HH_CONFIG||{};const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function header(){return `<header class="site-header"><div class="container nav"><a class="brand" href="./index.html"><img src="./images/logo/happy-hunger.svg" alt="Happy Hunger logo">Happy Hunger</a><button class="hamburger" aria-label="Open navigation" aria-expanded="false">☰</button><nav class="nav-links" aria-label="Main navigation"><a href="./index.html">Home</a><a href="./menu.html">Menu</a><a href="./recipes.html">Recipes</a><a href="./about.html">About</a><a href="./gallery.html">Gallery</a><a href="./contact.html">Contact</a><button class="icon-btn global-search" aria-label="Search dishes and recipes">⌕</button></nav></div></header>`}
function footer(){return `<footer class="site-footer"><div class="container footer-grid"><div><h2>Happy Hunger</h2><p>${C.tagline}</p><p class="status" id="openStatus"></p></div><div><b>Explore</b><div class="footer-links"><a href="./menu.html">Today's Menu</a><a href="./recipes.html">Recipes</a><a href="./feedback.html">Feedback</a><a href="./faq.html">FAQ</a></div></div><div><b>Info</b><div class="footer-links"><a href="./location.html">Location</a><a href="./contact.html">Contact</a><a href="./privacy.html">Privacy</a></div></div></div><div class="container"><small>© <span id="year"></span> Happy Hunger. Sample menu values are editable.</small></div></footer>`}
function inject(){const h=$('[data-header]'),f=$('[data-footer]');if(h)h.innerHTML=header();if(f)f.innerHTML=footer();$('#year')&&($('#year').textContent=new Date().getFullYear());const menu=$('.nav-links'),hamb=$('.hamburger');hamb?.addEventListener('click',()=>{menu.classList.toggle('open');hamb.setAttribute('aria-expanded',menu.classList.contains('open'))});}
function status(){const el=$('#openStatus');if(!el)return;const [sh,sm]=C.openingHours.start.split(':').map(Number),[eh,em]=C.openingHours.end.split(':').map(Number),d=new Date(),n=d.getHours()*60+d.getMinutes(),open=n>=sh*60+sm&&n<eh*60+em;el.textContent=open?'OPEN NOW':'CLOSED';el.classList.add(open?'open':'closed')}
function whatsapp(text='Hello Happy Hunger!'){window.open(`https://wa.me/${C.whatsapp}?text=${encodeURIComponent(text)}`,'_blank','noopener')}
function orderModal(dish=''){const m=$('#orderModal');if(!m)return;$('#orderDish',m).value=dish;m.classList.add('open');$('#orderName',m)?.focus()}
function initOrder(){const m=$('#orderModal');if(!m)return;$$('[data-order]').forEach(b=>b.addEventListener('click',()=>orderModal(b.dataset.order)));$('[data-close]',m)?.addEventListener('click',()=>m.classList.remove('open'));$('form',m)?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);whatsapp(`Hello Happy Hunger, I would like to order/enquire:\nDish: ${fd.get('dish')}\nQuantity: ${fd.get('qty')}\nDate: ${fd.get('date')}\nTime: ${fd.get('time')}\nName: ${fd.get('name')}\nMobile: ${fd.get('mobile')}\nMessage: ${fd.get('message')||''}`)})}
function commonModal(){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="orderModal" role="dialog" aria-modal="true" aria-label="Order enquiry"><div class="modal-box"><div class="modal-head"><h2>Order / Enquire</h2><button class="icon-btn" data-close aria-label="Close">✕</button></div><form><div class="field"><label>Name<input id="orderName" name="name" required></label></div><div class="field"><label>Mobile Number<input name="mobile" inputmode="tel" required></label></div><div class="field"><label>Dish<input id="orderDish" name="dish" required></label></div><div class="field"><label>Quantity<input name="qty" type="number" min="1" value="1" required></label></div><div class="field"><label>Preferred Date<input name="date" type="date" required></label></div><div class="field"><label>Preferred Time<input name="time" type="time" required></label></div><div class="field"><label>Message<textarea name="message"></textarea></label></div><button class="btn btn-primary" type="submit">Send Order on WhatsApp</button></form></div></div>`);document.body.insertAdjacentHTML('beforeend',`<div class="floating"><button class="float-btn" id="waFloat" aria-label="WhatsApp">✆</button><button class="float-btn backtop" id="backTop" aria-label="Back to top">↑</button></div>`);$('#waFloat').onclick=()=>whatsapp();$('#backTop').onclick=()=>scrollTo({top:0,behavior:'smooth'});initOrder()}
function toggleFav(type,id){const k='hhFavorites',a=JSON.parse(localStorage.getItem(k)||'[]'),key=`${type}:${id}`,i=a.indexOf(key);i>=0?a.splice(i,1):a.push(key);localStorage.setItem(k,JSON.stringify(a));return i<0}
function isFav(type,id){return JSON.parse(localStorage.getItem('hhFavorites')||'[]').includes(`${type}:${id}`)}
function initFav(){$$('[data-fav]').forEach(b=>{const [t,id]=b.dataset.fav.split(':');b.textContent=isFav(t,id)?'♥':'♡';b.addEventListener('click',()=>b.textContent=toggleFav(t,id)?'♥':'♡')})}
function search(){document.body.insertAdjacentHTML('beforeend',`<div class="search-pop" id="searchPop"><div class="search-box"><div class="modal-head"><h2>Search Happy Hunger</h2><button class="icon-btn" id="searchClose">✕</button></div><input id="globalSearchInput" aria-label="Search" placeholder="Search dishes or recipes..." style="width:100%;padding:14px;border:1px solid #ddd;border-radius:12px"><div id="globalResults" class="search-results"></div></div></div>`);const pop=$('#searchPop'),inp=$('#globalSearchInput'),out=$('#globalResults');function render(){const q=inp.value.toLowerCase().trim();const all=[...(window.HH_MENU||[]).map(x=>({...x,type:'Dish',url:`./dish.html?id=${x.id}`})),...(window.HH_RECIPES||[]).map(x=>({...x,type:'Recipe',url:`./recipe.html?id=${x.id}`}))].filter(x=>!q||`${x.name} ${x.desc}`.toLowerCase().includes(q));out.innerHTML=all.slice(0,12).map(x=>`<a href="${x.url}"><b>${x.name}</b> <small>• ${x.type}</small><br><small>${x.desc}</small></a>`).join('')||'<p>No matches found.</p>'}$$('.global-search').forEach(b=>b.onclick=()=>{pop.classList.add('open');render();inp.focus()});$('#searchClose').onclick=()=>pop.classList.remove('open');inp.oninput=render}
window.HH={whatsapp,orderModal,toggleFav,isFav,initFav};document.addEventListener('DOMContentLoaded',()=>{inject();commonModal();status();search();});})();
